# numpy 계산

In [1]:
import numpy as np

In [2]:
array1 = np.arange(10)
array2 = np.arange(10,20)

In [3]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [5]:
for i in range(len(array1)):
    array1[i] *= 2

In [6]:
array1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

#### 보통 배열 값에 2를 곱하고싶으면 위 처럼 for문을 이용하여 곱해야 하지만 ndarray는

In [7]:
array1 * 2

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

#### 그냥 곱하면 된다

In [8]:
a = [1,2,3,4]

In [9]:
a * 2

[1, 2, 3, 4, 1, 2, 3, 4]

####  그냥 리스트는 이런식으로 곱해짐

In [10]:
array1 / 2

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [11]:
array1 + 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [12]:
array1 ** 2

array([  0,   4,  16,  36,  64, 100, 144, 196, 256, 324], dtype=int32)

#### 모든 사칙연산 가능

In [13]:
array1 = np.arange(10)

In [14]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
array1 + array2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

#### ndarray끼리 연산 가능

---

In [17]:
array3 = np.arange(1,11)
array3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
array3 > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

#### bool 연산도 가능

In [19]:
booleans = array3 % 2 == 0
booleans

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [20]:
np.where(booleans)

(array([1, 3, 5, 7, 9], dtype=int64),)

#### true인 값만 뽑아내는 np.where함수

In [21]:
np.where(array3 > 4)

(array([4, 5, 6, 7, 8, 9], dtype=int64),)

#### where함수를 이런식으로도사용가능

In [22]:
filter = np.where(array3 > 4)

In [23]:
array3[filter]

array([ 5,  6,  7,  8,  9, 10])

#### where를 이용하여 만든 filter를 이용하여 인덱싱 가능

In [24]:
array3[np.where(array3 > 4)]

array([ 5,  6,  7,  8,  9, 10])

---

In [25]:
array3.max()

10

In [26]:
array3.min()

1

#### mean은 평균값

In [29]:
print(array3.mean())

5.5


#### np.median 은 중앙값을 출력해주는데 짝수개 일때는 가운데 두 수의 평균을 출력한다

In [33]:
array3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
np.median(array3)

5.5

In [36]:
array3 = [1,2,3,4,5,6,7,8,9]
array3

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [38]:
np.median(array3)

5.0

---

#### 표준편차, 분산

In [46]:
array4 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

In [47]:
array4.std() # 표준편차

8.496322733983215

In [48]:
array4.var() # 분산

72.1875

In [52]:
array5 = np.array([13,12,11,10,14,15,16,17])

In [53]:
array5.std()

2.29128784747792

In [54]:
array5.var()

5.25

In [58]:
array6 = np.array([1,2,3,4,20,30,40])

In [59]:
array6.std()

14.645470150130633

In [60]:
array6.var()

214.48979591836738

#### 표준편차와 분산이 작을수록 각 요소들이 평균가까이에 모여있다